run_mac: 
	javac -cp ".:acm.jar:jinput.jar:" OneButtonTracker.java *.java
	java  -cp ".:acm.jar:jinput.jar:" OneButtonTracker
run_windows:
	javac -cp ".;acm.jar;jinput.jar;" OneButtonTracker.java *.java
	java  -cp ".;acm.jar;jinput.jar;" OneButtonTracker
     